# tomcat
server:
  port: 8090
  servlet:
    context-path: /weare


# spring
spring:
  thymeleaf:
    prefix : classpath:/templates/
    suffix : .html
    cache : false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/weare
    username: root
    password: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    converters:
      preferred-json-mapper: gson
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# logback
logging:
  level:
    root: info
    '[com.ep.weare]': debug

# file
file:
  upload:
    directory:
      kelly: C:/weareAttach/kelly
      announceAttach: C:/weareAttach/announceAttach
      ministryAttach: C:/weareAttach/ministryAttach
      executivesAttach: C:/weareAttach/executivesAttach